language: php

php:
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
  - vendor/bin/humbug
  - ./build/check-humbug-mutators.php
  - vendor/bin/infection --threads=4 --min-msi=96 --min-covered-msi=96

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
